# Generated by Django 3.1.1 on 2020-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vector',
            field=models.BinaryField(blank=True),
        ),
    ]
