# Generated by Django 3.1.1 on 2020-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200925_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vector',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
